modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/DaRealTurtyWurty/TurtyChemistry/issues"

[[mods]]
modId = "turtychemistry"
version = "1.0-DEV"
displayName = "Turty's Chemistry"
updateJSONURL = "https://raw.githubusercontent.com/DaRealTurtyWurty/TurtyChemistry/main/updates.json"
displayURL = "https://github.com/DaRealTurtyWurty/TurtyChemistry/"
logoFile = "logo.png"
credits = ""
authors = "TurtyWurty"
description = '''
A mod for minecraft which adds chemistry into the game.
'''