name: Java Code Formatting

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v3.6.0
