# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    - uses: burrunan/gradle-cache-action@v1
      with:
          arguments: build
          # Read-only cache if not on repo's default branch: https://stackoverflow.com/a/68414395
          read-only: ${{ format('refs/heads/{0}', github.event.repository.default_branch) != github.ref }}
          gradle-dependencies-cache-key: |
            gradle/gradle.properties
          gradle-distribution-sha-256-sum-warning: false
